# GitHub Action that runs pytest

name: Run Pytest
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --exitfirst --verbose --failed-first --cov-report=term-missing --cov-report=xml tests/
      - name: Run tests
        run: |
          pip install genbadge[coverage]         
          genbadge coverage -i coverage.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-badge
          path: coverage-badge.svg