# GitHub Action that runs pytest with the oldest packages specified

name: Run Pytest
on:
  workflow_dispatch:
  push:
  schedule:
    # execute once a week on monday 
    - cron:  '30 0 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: |
          pip install matplotlib==3.4.1 numpy==1.20.2 pandas==1.2.4 scikit-learn==0.24.1
          pip install .
          pip install pytest
          pip install pytest-cov
      - name: Run tests
        run: |
          pytest --exitfirst --verbose --failed-first --cov=src tests/ --cov-report=term-missing --cov-report=xml